name: Feature Branch

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'yarn'
    - run: yarn
    - run: yarn pack:zip

    - name: package-version  
      uses: nyaa8/package-version@v1.0.3
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: 'aquaTestRecorder-v.${{ env.PACKAGE_VERSION }}'
        path: extension.zip
