name: Master Branch

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'yarn'
    - run: yarn

    # Get current version
    # - name: package-version  
    #   uses: nyaa8/package-version@v1.0.3

    # Get next release version
    # - name: Bump release version
    #   id: bump_version
    #   uses: christian-draeger/increment-semantic-version@1.0.2
    #   with:
    #     current-version: ${{ env.PACKAGE_VERSION }}
    #     version-fragment: 'feature'

    # - name: 'Update version'
    #   run: |
    #     git config --global user.name 'Github'
    #     git config --global user.email 'AquaActions@users.noreply.github.com'
    #     npm version ${{ steps.bump_version.outputs.next-version }}
    #     git push -u origin HEAD

    # - run: yarn pack:zip

    # Release version along with the zipped extension as assets
    # - uses: ncipollo/release-action@v1
    #   with:
    #     artifacts: "extension.zip"
    #     tag: v${{ steps.bump_version.outputs.next-version }}

    # - name: Checkout Public repo
    #   uses: actions/checkout@v2
    #   with:
    #     repository: farazshuja/chrome_ext_public
    #     path: extpublic
    #     ref: 'master'
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     fetch-depth: 0
    
    # - name: Create file
    #   run: |
    #     git status
    #     echo "Test secret . ${{ secrets.GITHUB_TOKEN }}"
    #     echo "Hello you!" >> README.md
    #   working-directory: extpublic

    - uses: GuillaumeFalourd/git-commit-push@v1.3
      with:
        email: AquaActions@users.noreply.github.com
        name: AquaActions
        commit_message: here is my message
        target_branch: main
        files: README.md
        remote_repository: https://github.com/farazshuja/chrome_ext_public
        access_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
        empty: true
        tags: true

    # - name: Update file
    #   run: |
    #     git status
    #     ls
    #     echo "Test secret . ${{ secrets.GITHUB_TOKEN }}"
    #     echo "Hello you!" >> README.md
    #     git config --global user.name 'Github'
    #     git config --global user.email 'AquaActions@users.noreply.github.com'
    #     git add .
    #     git commit -m "update it"
    #     ls
    #     git status
    #     git push -u origin HEAD
    #   working-directory: extpublic
    
    # Push the new version to public repo
    # - name: Pushes the release to public repo
    #   uses: dmnemec/copy_file_to_another_repo_action@main
    #   env:
    #     API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     source_file: 'extension.zip'
    #     destination_repo: 'farazshuja/chrome_ext_public'
    #     destination_branch: 'master'
    #     user_email: 'AquaActions@users.noreply.github.com'
    #     user_name: 'Github'
    #     commit_message: 'Release v${{ steps.bump_version.outputs.next-version }}'

    # - name: Pushes to another repository
    #   uses: cpina/github-action-push-to-another-repository@main
    #   env:
    #     API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     source-directory: 'extension'
    #     destination-github-username: 'farazshuja'
    #     destination-repository-name: 'chrome_ext_public'
    #     user-email: 'AquaActions@users.noreply.github.com'
    #     target-branch: 'master'
    # will print 2.12.0
    # - name: Upload a Build Artifact
    #   uses: actions/upload-artifact@v2.3.1
    #   with:
    #     name: 'aquaTestRecorder-v.${{ env.PACKAGE_VERSION }}'
    #     path: extension.zip
